name: Security Analysis

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run SAST with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Run DAST with OWASP ZAP
      uses: zaproxy/action-full-scan@v0.9.0
      with:
        target: 'https://your-deployed-app.com'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-scan-report
        path: report.html
        retention-days: 30
