name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Rulează doar pe main, poți modifica pentru alte branch-uri

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Sau 'yarn install' dacă folosești Yarn

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=MVamanu \
            -Dsonar.projectKey=mvamanu \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.sources=src \
            -Dsonar.language=TypeScript \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
